### PR TITLE
Combine xin fab xin che jian

### PR DESCRIPTION
**Pull request by rngadam**

### CODE REVIEW

**Comment by lpgn** [comment]
@emj365 can you help out here? not good in command line so cant really merge this.

**Comment by emj365** [comment]
```
<<<<<<< 87d77e604d436028227fc1c8003e7943b52eeb77
# **XinFab 新Fab and Xinchejian 新车间** 
# **Liability Waiver**

* As a FabLab and also a community of makers, 比特奥特姆（上海）印刷科技有限公司 （“XinFab 新Fab”）and 信彻坚电子科技（上海）有限公司 ("Xinchejian 新车间"), provides their facilities, equipment, classes, and activities with the intention of creating an environment that supports collaboration, creation, and community among its participants (“Makers”). To this end, XinFab 新Fab and XinCheJian 新车间 take reasonable precautions to maintain safety of their space and equipment but cannot guarantee the safety of the Makers at all times.

* I acknowledge that these risks cannot be eliminated without jeopardizing the essential and/or fundamental qualities of XinFab 新Fab and Xinchejian 新车间, and their activities and events. I agree and promise to accept and assume personal responsibility for all potential risks that exist from my participation at XinFab 新Fab and Xinchejian 新车间, including but not limited to risks that are known and unknown, anticipated and unanticipated, despite XinFab 新Fab and Xinchejian 新车间’s reasonable efforts toward safety, despite perceived negligence by XinFab 新Fab and Xinchejian 新车间, and other faults.
=======
# **XinFab 新Fab and Xinchejian 信彻坚电子科技（上海）有限公司 Liability Waiver**

* As a FabLab and also a community of makers, 比特奥特姆（上海）印刷科技有限公司 （“XinFab 新Fab”）and 信彻坚电子科技（上海）有限公司 ("Xinchejian 新车间"), provides their facilities, equipment, classes, and activities with the intention of creating an environment that supports collaboration, creation, and community among its participants (“Makers”). To this end, XinFab 新Fab and XinCheJian 新车间 take reasonable precautions to maintain safety of their space and equipment but cannot guarantee the safety of the Makers at all times.

* I acknowledge that these risks cannot be eliminated without jeopardizing the essential and/or fundamental qualities of XinFab 新Fab & Xinchejian 新车间, and their activities and events. I agree and promise to accept and assume personal responsibility for all potential risks that exist from my participation in XinFab 新Fab and Xinchejian 新车间, including but not limited to risks that are known and unknown, anticipated and unanticipated, despite XinFab 新Fab and Xinchejian 新车间’s reasonable efforts toward safety, despite perceived negligence by XinFab 新Fab and Xinchejian 新车间, and other faults.
>>>>>>> Update waiver.md

* My participation is purely voluntary, and I agree that if at any time I believe conditions to be unsafe, I will immediately discontinue further participation in the activity. I also accept and agree to abide by any and all safety procedures established in XinFab 新Fab and Xinchejian 新车间(especially as relevant to my participation) and to exercise rationality and sound judgment. I agree to utilize only the equipment and areas in XinFab 新Fab and XinCheJian 新车间, and participate only in the activities and events, that are within the scope of my training and knowledge. Furthermore, I agree to report any accident, malfunction, or breakdown of equipment or facilities to the appropriate member of XinFab 新Fab and Xinchejian 新车间.

* I further acknowledge that inherent risks, dangers and hazards and such exist when using power tools commonly used in electronics construction, fabrication, software design and other technology-related activities. Participation in such activities and/or the use of equipment associated with technology design, fabrication or manufacture and experimentation may result in injury, illness, death or damage to personal property.

* I fully assume all risks associated with participation in events and exempts and release XinFab 新Fab and Xinchejian 新车间, their members, officers, agents and board members, from action whatsoever arising out of any damage, loss or injury to me or my property while upon the premises or using any equipment of XinFab 新Fab and Xinchejian 新车间 or while participating in any of the activities contemplated by this agreement whether such loss, damage, or injury results from the negligence of XinFab 新Fab and Xinchejian 新车间, their members, agents, or from some other cause.

* I will indemnify, save and hold harmless XinFab 新Fab and Xinchejian 新车间, their members, officers, board members, and agents from any and all losses, claims, actions, or proceedings of every kind and character which may be presented or initiated by any other persons or organizations and which arise directly or indirectly from my actions while engaged in the activities contemplated by this agreement.

* I hereby acknowledge that I have CAREFULLY read all of the provisions above, fully understand the terms and conditions expressed there, and I intend it to be a complete and unconditional release of all liability to the greatest extent allowed by law. Should any portion of this agreement be held to be invalid, its remainders shall continue to be in effect.




__________________________________________________________(Print and Sign Name)____________(Date)




if signing on behalf of minor, Minor's Name:______________________________________________________________

based on the [Novalabs](http://nova-labs.org/blog/) waiver
```

@lpgn Take time to check the text above, you can see conflicts.
Please make your new version manually, then paste here. I will commit it.

**Comment by emj365** [comment]
@rngadam glad to see you here. I owe you a dinner.

**Comment by lpgn** [comment]
# **XinFab 新Fab and Xinchejian  新车间 Liability Waiver**
- As a FabLab and also a community of makers, 比特奥特姆（上海）印刷科技有限公司 （“XinFab 新Fab”）and 信彻坚电子科技（上海）有限公司 ("Xinchejian 新车间"), provides their facilities, equipment, classes, and activities with the intention of creating an environment that supports collaboration, creation, and community among its participants (“Makers”). To this end, XinFab 新Fab and XinCheJian 新车间 take reasonable precautions to maintain safety of their space and equipment but cannot guarantee the safety of the Makers at all times.
- I acknowledge that these risks cannot be eliminated without jeopardizing the essential and/or fundamental qualities of XinFab 新Fab and Xinchejian 新车间, and their activities and events. I agree and promise to accept and assume personal responsibility for all potential risks that exist from my participation in XinFab 新Fab and Xinchejian 新车间, including but not limited to risks that are known and unknown, anticipated and unanticipated, despite XinFab 新Fab and Xinchejian 新车间’s reasonable efforts toward safety, despite perceived negligence by XinFab 新Fab and Xinchejian 新车间, and other faults.
- My participation is purely voluntary, and I agree that if at any time I believe conditions to be unsafe, I will immediately discontinue further participation in the activity. I also accept and agree to abide by any and all safety procedures established in XinFab 新Fab and Xinchejian 新车间(especially as relevant to my participation) and to exercise rationality and sound judgment. I agree to utilize only the equipment and areas in XinFab 新Fab and XinCheJian 新车间, and participate only in the activities and events, that are within the scope of my training and knowledge. Furthermore, I agree to report any accident, malfunction, or breakdown of equipment or facilities to the appropriate member of XinFab 新Fab and Xinchejian 新车间.
- I further acknowledge that inherent risks, dangers and hazards and such exist when using power tools commonly used in electronics construction, fabrication, software design and other technology-related activities. Participation in such activities and/or the use of equipment associated with technology design, fabrication or manufacture and experimentation may result in injury, illness, death or damage to personal property.
- I fully assume all risks associated with participation in events and exempts and release XinFab 新Fab and Xinchejian 新车间, their members, officers, agents and board members, from action whatsoever arising out of any damage, loss or injury to me or my property while upon the premises or using any equipment of XinFab 新Fab and Xinchejian 新车间 or while participating in any of the activities contemplated by this agreement whether such loss, damage, or injury results from the negligence of XinFab 新Fab and Xinchejian 新车间, their members, agents, or from some other cause.
- I will indemnify, save and hold harmless XinFab 新Fab and Xinchejian 新车间, their members, officers, board members, and agents from any and all losses, claims, actions, or proceedings of every kind and character which may be presented or initiated by any other persons or organizations and which arise directly or indirectly from my actions while engaged in the activities contemplated by this agreement.
- I hereby acknowledge that I have CAREFULLY read all of the provisions above, fully understand the terms and conditions expressed there, and I intend it to be a complete and unconditional release of all liability to the greatest extent allowed by law. Should any portion of this agreement be held to be invalid, its remainders shall continue to be in effect.

__________________________________________________________(Print and Sign Name)____________(Date)

if signing on behalf of minor, Minor's Name:______________________________________________________________

based on the [Novalabs](http://nova-labs.org/blog/) waiver

**Pull request closed without merging**
